export const productData = [
  {
    id: 1,
    name: "MacBook Pro 16'",
    price: "2,699.99",
    category: "MacBook",
    image: "https://i.ibb.co.com/MVkKH4x/image.png",
    description: "14-inch laptop with M4 Pro chip",
    status: "In Stock",
    specifications: ["M4 Pro chip", "30GB RAM", "2TB SSD", "16-inch Liquid Cornia XDR"],
    rating: 4.8,
  },
  {
    id: 2,
    name: "MacBook Pro 14'",
    price: "1,999.99",
    category: "MacBook",
    image: "https://i.ibb.co.com/GpFs7QD/t-Ln-RAETiy-Vx-RDDioj-NUAXX-1200-80.jpg",
    description: "Powerful laptop with M2 Pro chip",
    status: "In Stock",
    specifications: ["M2 Pro chip", "16GB RAM", "512GB SSD", "14-inch Liquid Retina XDR"],
    rating: 4.8,
  },
  {
    id: 3,
    name: "iPhone 15 Pro",
    price: "999.99",
    category: "iPhone",
    image: "https://i.ibb.co.com/TvKL56N/i-Phone-15-Pro-003-1.webp",
    description: "A17 Pro chip, 48MP camera",
    status: "In Stock",
    specifications: ["A17 Pro chip", "6.1-inch Super Retina XDR display", "48MP Main Camera", "5G Connectivity"],
    rating: 4.7,
  },
  {
    id: 4,
    name: "Samsung Galaxy S24",
    price: "899.99",
    category: "Phones",
    image: "https://i.ibb.co.com/NnNYTYV/9f08cb61d1f5846e27bc4ec9e590af57-jpg-2200x2200q80-jpg-1.webp",
    description: "6.8-inch QHD+ display",
    status: "In Stock",
    specifications: ["Snapdragon 8 Gen 3", "6.8-inch QHD+ AMOLED display", "50MP Triple Camera", "5000mAh Battery"],
    rating: 4.6,
  },
  {
    id: 5,
    name: "Apple Watch Series 9",
    price: "399.99",
    category: "Smart Watches",
    image: "https://i.ibb.co.com/sKRcTqC/dsc02871-enhanced-nr.webp",
    description: "Always-On Retina display",
    status: "In Stock",
    specifications: ["S9 Chip", "Always-On Retina display", "Blood Oxygen Sensor", "Water Resistant"],
    rating: 4.9,
  },
  {
    id: 6,
    name: "AirPods Pro",
    price: "249.99",
    category: "Accessories",
    image: "https://i.ibb.co.com/qdHTX7t/Apple-Air-Pods-Pro-3-release-date-predictions-price-specs-and-must-know-features-1.jpg",
    description: "Active Noise Cancellation",
    status: "In Stock",
    specifications: ["Active Noise Cancellation", "Transparency mode", "Spatial audio", "Wireless charging case"],
    rating: 4.7,
  },
  {
    id: 7,
    name: "MacBook Air",
    price: "999.99",
    category: "MacBook",
    image: "https://i.ibb.co.com/b2sgLsP/06-MB2dd9-IF24om-R8kjq-GL2v-4.webp",
    description: "13.6-inch Liquid Retina display",
    status: "In Stock",
    specifications: ["M2 chip", "8GB RAM", "256GB SSD", "13.6-inch Liquid Retina display"],
    rating: 4.6,
  },
  {
    id: 8,
    name: "iPhone 13",
    price: "799.99",
    category: "iPhone",
    image: "https://i.ibb.co.com/j5BGGgq/35-M23-Sa-Drt-Qvge4-Eo-XWTVC-1920-80-jpg.webp",
    description: "A16 Bionic chip",
    status: "In Stock",
    specifications: ["A16 Bionic chip", "6.1-inch Super Retina XDR display", "Dual 12MP Camera", "5G Connectivity"],
    rating: 4.5,
  },
  {
    id: 9,
    name: "ThinkPad X1 Carbon",
    price: "1,399.99",
    category: "Laptops",
    image: "https://i.ibb.co.com/tYnrLzb/ucxy-Hcdo-J276-K3ythh-RDBZ-1920-80-jpg.webp",
    description: "14-inch business laptop",
    status: "In Stock",
    specifications: ["Intel i7 12th Gen", "16GB RAM", "512GB SSD", "14-inch FHD display"],
    rating: 4.4,
  },
];
